POST localhost:8080/characters
Accept: application/json
Content-Type: application/json


{
    "name": "Chronie",
    "statistics" : {
        "weakness": "DEXTERITY",
        "medium": "FORCE",
        "strength": "INTELLIGENCE"
    },
    "species" : "GNOME",
    "profile": "WIZARD",
    "equipment": {
        "TORSO": {
            "name": "CHAIN_MAIL",
            "attrition": 100
        },
        "HANDS": {
            "name": "STAFF",
            "attrition": 100
        }
    }
}

###

POST localhost:8080/encounters
Content-Type: application/json

{
  "characterId" : "63c1669a5ec73b7a99d19067",
  "grid" : "SQUARE_8",
  "brain" : {
    "type": "REMOTE",
    "uri": "http://localhost:8083/brain"
  }
}


###

POST localhost:8082/encounters/63c166ef9e2a2775f4a70b06:launch