rpg-web:
  encounter-manager:
    host: localhost
    port: 8082
    protocol: http
spring:
  data:
    mongodb:
      username: rpg-arena
      password: change-me
      host: localhost
      port: 27017
      database: rpg-arena
      authentication-database: rpg-arena
server:
  port: 8084