server:
  port: 8082
spring:
  data:
    mongodb:
      username: rpg-arena
      password: change-me
      host: localhost
      port: 27017
      database: rpg-arena
      authentication-database: rpg-arena